### ISSUE TITLE
create placeholders for "future doc" ideas

### ISSUE THREAD

**Issue by taradiddles** [Qubes-Community/Contents#10]
[EDIT: agreed to file 'doc suggestion' issues with a leading 'Doc suggestion: blah' title]

Problem: people usually don't have time to write a nice doc from an insightful ML thread as soon as they read an interesting one, or to put a nice doc idea onto paper just when they're thinking about it. It's then too easy to forget about it later.

This issue is about agreeing on how to file "future doc ideas" so that
- insightful ML posts, ideas, ... aren't forgotten
- we avoid duplicated work since everybody can see what's been working on.
- anyone can pick a "future doc" task and transform it into a proper doc page/hint.

Suggestion: open an issue with a "Doc suggestion: blahblah" title, and put a link in the body to the related ML thread, or a quick explanation of the idea.

~~~Alternative: create a project and use tasks - but I have no idea how it works, if there's public access, etc~~~ [edit: tasks are in fact issues]

The issue (or task) could then be transformed into a PR or pushed to the doc with a direct commit as described in the other workflows.

Examples of interesting posts of the last 2 weeks:
- dpi/highres displays (not necessarily qubes related, but VMs make it a bit more involved).
- copying sparse files to dom0
- bash autocomplete
- debugging hints
- coreboot
- disk space in R4
- dns propagation

**Comment by Aekez** [comment]
It's a good idea, I feel fretty much feel the same way about it as well, ideas are quickly lost, unmentioned, or inspiration doesn't get an opportunity, So I don't just think it's a good idea, I think it's a very good idea. 

Project tasks can be made with issues, try look in QubesTV, you'll see a small scale easy to keep overview example. That way, issues can be used, but they can be tracked in an indifinite amount of projects, with indifinite amount of items on each lists, though I believe each projects list is finite, but I'm not sure.

This way if people post in issues about a good idea, we can just select a project in the right panel, and then later sort it out in projects :) well one way to do it, I'm of course open for other tracking system suggestions as well.

Maybe also keep an issue for smaller issues that doesn't require a full issue, which can serve as a double-function for people to discuss if an issue is good enough to be posted (if people are in doubt). It might also put some people off if they cannot delete the issue it self, but they can easily delete their own comments on an issue though. So it might be more attractive for "some" people if they can keep control (i.e. if they regreet posting the idea, for example if the idea doesn't work very well). Though the everlasting burning question of communities; should people be allowed to delete their own content or not?

**Comment by Aekez** [comment]
any issue posted with a good idea ---> moderator/reviewer/owner/whoever-with-rights can then assign it to a project (which there can be multiple or many different ones of), and then inside the project tab, they can be assigned a specific tab in projects, i.e. progress or whichever one may want to name these tabs. 

For example we could have a project for ideas that need developers, and ideas which already has a developer, or mixed ones with having developers but needs more developers. We can also make a single project instead for all 3 of these, and then make a tab for each one. or some other ideas, we have some flexibility here, assuming we use projects and not something else. 

Projects seems nice and easy though, since it's integrated with issues.

**Comment by Aekez** [comment]
Just tested QubesTV, it can be seen publicly too without login :) feel free to try temporarily changing visibility settings in QubesTV to see what differences it makes.

**Comment by taradiddles** [comment]
Thanks for testing the project stuff !

Judging by github's "project presentation" page I thought there would be a simple "task manager" independent from issues (it's actually quite well made, although overkill for the project imho, at least at the beginning). Anyway if it's linked to issues then it basically answers my question: use issues for quick doc suggestions/ideas.

Tagging issues requires write rights, which I don't think a lot of people will have, so to avoid loosing time understanding the content of the issue, we could advise contributors to use a title like 'Suggestion: ...' or something like that (it's of course left to the user not to forget it). Thoughts ?

**Comment by taradiddles** [comment]
@awokd , thoughts on this issue ?

**Comment by awokd** [comment]
> "Doc suggestion: blahblah" 

sounds good. I know I have a backlog of emails I've saved with helpful tips to put "somewhere" that don't quite qualify as FAQs but are still useful information.

**Comment by taradiddles** [comment]
OK; I've updated the landing page doc about those suggestions.
closing then...

**Comment by taradiddles** [comment]
re-opening for a quick question: I had a bit of time and created a doc suggestion issue (#11); As agreed, the title begins with `Doc suggestion: `

Q: once one of us assigns the "doc-suggestion" label to such issues, should we edit the title to remove the now redundant `Doc suggestion: `, or should we simply leave the title as-is ?

**Comment by awokd** [comment]
Let's leave the title as is; I imagine we'll get some titles that aren't formatted correctly too, but we can just look for the tag.

**Comment by taradiddles** [comment]
ok - that's what I thought too.
re-closing :)
