### ISSUE TITLE
Question about MFA

### ISSUE THREAD

**Issue by hxr404** [Qubes-Community/Contents#104]
I found this at the Whonix documentation: [Two-factor Authentication (2FA)](https://www.whonix.org/wiki/Two-factor_authentication_2FA). It seems like this *KeePassXC* has a GUI. But is it as secure as your solution?
Sorry if this Question was stupid

Thanks

**Comment by awokd** [comment]
Not sure to which solution you're referring. Qubes in general, or a specific document on this site?

**Comment by hxr404** [comment]
![grafik](https://user-images.githubusercontent.com/55095883/102482967-57455180-4064-11eb-8120-54f0d6c16ce0.png)
This is a tutorial how to install [KeepassXC](https://www.whonix.org/wiki/Keepassxc) on Qubes-Os

**Comment by awokd** [comment]
Can you also link to the document here you are comparing?

**Comment by hxr404** [comment]
this: https://github.com/Qubes-Community/Contents/blob/master/docs/security/multifactor-authentication.md
vs: this https://www.whonix.org/wiki/Keepassxc

**Comment by awokd** [comment]
Thank you. They seem about the same to me, except one uses KeepassXC and the other oathtool. The Qubes one describes in more detail how to configure an offline AppVM, but it is also recommended on the Whonix document. Make sense?
