### ISSUE TITLE
Arch Linux Template fails to build.

### ISSUE THREAD

**Issue by user1064** [Qubes-Community/Contents#106]
Failure happens at `make vmm-xen-vm` while attempting to execute `patch-xen-gcc10-fixes.patch` on the file `tools/xenstore/xenstored_core.h`.

Extra notes:

When you time out while downloading a package in chroot the packages do not get installed but the script continues and you need to go and manually install them. First time I timed out, I was able to re-run `make qubes-vm` and it downloaded the base packages but when it proceeded to `base-devel` and timed out again, it continued to `vmm-xen-vm` makefile.

`sudo BACKEND_VMM=xen chroot "/home/user/qubes-builder/chroot-vm-archlinux"`

**Comment by awokd** [comment]
I think this issue might be better opened over on qubes-os instead, unless there is some documentation here you think should be changed?

**Comment by user1064** [comment]
> I think this issue might be better opened over on qubes-os instead, unless there is some documentation here you think should be changed?

I imagined this is a Community project therefore the participants are responsible for the fixes/documentation on how to successfully build, but it appears I am mistaken?

**Comment by awokd** [comment]
@user1064 Might be my error too, if the documentation is here then please submit a correction!

**Comment by kevinjohna6** [comment]
I think this is related: [qubes-issues#6357](https://github.com/QubesOS/qubes-issues/issues/6357)

There are a couple documented "patches" there that we could include in the build documentation/troubleshooting, but I'm not sure that they consistently fix the problem.

**Comment by lubellier** [comment]
Hi @user1064 ,
  I think this issue is now deprecated, I built the 4.1 template without this issue, so could you try again?
