### ISSUE TITLE
Update qubes-doc index for split-ssh

### ISSUE THREAD

**Issue by deeplow** [Qubes-Community/Contents#107]
The [split-ssh documentation has recently been created](https://github.com/Qubes-Community/Contents/blob/master/docs/configuration/split-ssh.md), but the qubes-doc index [is still pointing](https://www.qubes-os.org/doc/#security-guides) to kushalda's blog post.

@awokd would you be able to open a PR against qubes-doc for updating this there?

Source: https://github.com/QubesOS/qubes-issues/issues/4693#issuecomment-751268118

**Comment by awokd** [comment]
https://github.com/QubesOS/qubes-doc/pull/1106. Thanks for getting this coordinated. Please feel free to point out any others that should be updated. I'll check too.

**Comment by awokd** [comment]
Merged.
