### ISSUE TITLE
Doc suggestion: change dpi scaling uniformly in dom0 and VMs

### ISSUE THREAD

**Issue by taradiddles** [Qubes-Community/Contents#11]
goal: change dpi scaling for people with high resolution displays and/or who can't read tiny fonts.

Tasks:
- [x] add instructions from the official issue
- [ ] test instructions on R3.2 (with various apps, if possible with different toolkits - gtk, qt, ...)
- [x] test instructions on R4.0 (with various apps, if possible with different toolkits - gtk, qt, ...)

---

Qubes OS passes the screen resolution on to VMs (see the output of `xrandr`) but doesn't pass dom0's dpi setting. Recent distributions have automatic scaling (eg. in fedora if the vertical resolution is greater than 1200px) but it's usually best to set a custom dpi scaling value that fits one's setup.

#### dom0:

- xfce: Qubes Menu → System Tools → Appearance → Fonts tab: Custom DPI setting: 120 (change accordingly - default value is 96)
- kde (untested): Qubes Menu → System Settings → Font → Force font dpi: enter a number such as 125, 144 or 150 etc

#### VMs - R3.2

fixme: untested ; does that work only for gnome apps ?  why doesn't the xft.dpi resource tweak work with R3.2 ?

~~~
gsettings set org.gnome.desktop.interface scaling-factor 2
gsettings set org.gnome.desktop.interface text-scaling-factor 0.75
~~~

fixme: tested ok with:
- [ ] firefox
- [ ] google-chrome
- [ ] libreoffice
- [ ] gimp
- [ ] eog

#### VMs - R4.0

Set the Xft.dpi X resource.

Get the current value:

~~~
xrdb -query | grep Xft.dpi
~~~

Test with a different dpi value: in a terminal issue the following command and then start an application to check that the menus/fonts' size is increased/decreased (replace '144' accordingly):

~~~
echo Xft.dpi: 144 | xrdb -merge
~~~

You may then set the dpi resource persistently by adding a `Xft.dpi: xxx` line (replace 'xxx' accordingly):
- to the TemplateVM's Xresource file (`/etc/X11/Xresources` or `/etc/X11/Xresources/x11-common` for whonix-ws-template).
- or, to the .Xresources file in *each* VM's user profile (`$HOME/.Xresources`)

fixme: tested ok on R4.0 (final) with:
- [x] firefox
- [x] google-chrome
- [x] libreoffice
- [x] gimp
- [x] eog
- [x] qgis

#### Resources

related official issue: https://github.com/QubesOS/qubes-issues/issues/1951

**Comment by taradiddles** [comment]
anyone can test on R3.2 ? Alternatively, remove the 3.2 instructions and focus only on R4.x

**Comment by awokd** [comment]
Can't test on R3.2 any time soon - maybe leave as is with a note they "should" work but are untested?

**Comment by taradiddles** [comment]
closing - https://github.com/Qubes-Community/Contents/blob/master/docs/customization/dpi-scaling.md
