### ISSUE TITLE
i915.alpha_support has been renamed (again), documentation needs updating

### ISSUE THREAD

**Issue by bxatnarf** [Qubes-Community/Contents#122]
In the [Intel Integrated Graphics Troubleshooting](https://github.com/Qubes-Community/Contents/blob/master/docs/troubleshooting/intel-igfx-troubleshooting.md#software-rendering-or-video-lags) guide, it suggests setting `i915.alpha_support=1`.  This option was removed from the kernel in [this commit](https://github.com/torvalds/linux/commit/eea4262a4b598df7ea75201d564e4627b4408359). According to the commit `i915.force_probe` should be used instead.

**Comment by awokd** [comment]
Thanks for the catch, that's like the third time they renamed it. You comfortable submitting a pull request to change the doc., or prefer I do it?

**Comment by bxatnarf** [comment]
The one caveat is that, unlike its predecessors, `force_probe` is not a boolean option -- https://github.com/torvalds/linux/blob/7ef5ef5cdead61b8bc17493aae565962611a2918/drivers/gpu/drm/i915/Kconfig#L51 

Its value can be set to `*` to instruct the kernel to "force probe the driver for all known devices", which I assume is equivalent to `i915.alpha_support=1`.  Pull request -- https://github.com/Qubes-Community/Contents/pull/123

**Comment by awokd** [comment]
Thanks again!
