### ISSUE TITLE
Archlinux template vmm-xen-vm build python2-lxml crash

### ISSUE THREAD

**Issue by xwallacex** [Qubes-Community/Contents#126]
Hello,
during archlinux build I have encountered crash during `$ make vmm-xen-vm` with missing dependencies `python2-lxml`. 
For the fix, I have changed  in `~/qubes-builder/qubes-src/vmm-xen/archlinux/PKGBUILD` `python2-lxml` for `python-lxml`.
[qubes-vmm-xen/archlinux/PKGBUILD](https://github.com/QubesOS/qubes-vmm-xen/blob/xen-4.14/archlinux/PKGBUILD) for xen 4.14 already has correct python-lxml dep.
I think the issue may be that builder uses PKGBUILD from older xen version (eg. 4.13).

**Comment by awokd** [comment]
I think you would want to commit a fix somewhere in https://github.com/QubesOS/qubes-builder-archlinux. It's a different project than this one, but if you have trouble finding where to apply your fix I can help look.

**Comment by awokd** [comment]
Please reopen or comment if you can't find.
