### ISSUE TITLE
Community-created Simple User Guide

### ISSUE THREAD

**Issue by deeplow** [Qubes-Community/Contents#127]
Hi @awokd. Just wanted to point out to [this discussion](https://qubes-os.discourse.group/t/community-created-simple-user-guide/3678) about making a simple user guide. Not sure if it would belong in this repo (probably) not, but just using this as an opportunity to call it to your attention.

**Comment by awokd** [comment]
Thanks for the heads up. Am happy to host here, though as mentioned in the referenced thread, wiki is probably a lower barrier to entry.
