### ISSUE TITLE
Doc suggestion: DNS over https / tls / ...

### ISSUE THREAD

**Issue by taradiddles** [Qubes-Community/Contents#14]
^ title.

this subject comes back often in the ML  ; it looks pretty easy to implement but there are different opinions on how to do that best (attack surface / proxyVM / ...).

https://groups.google.com/d/msgid/qubes-users/9XVz-7viQEqd-6MPx8NvR4Fnk502VgBDJUYogFE056xaFr-k76ApY7WmEbi3oH6yQZQ7MEHbuqYbwCZInJ8LE9lysw_e3w8Dw93FrISL2hU%3D%40micahflee.com

edit: related upstream issue: https://github.com/QubesOS/qubes-issues/issues/3782
edit: updated title

**Comment by Aekez** [comment]
@taradiddles 
I never quite found out if it is deemed safe to construct multiple internal networks in Qubes OS. Like for example, multiple sys-firewall's connecting to the same sys-net, or going even further, having multiple sys-net's with each their own connection and sys-firewall. 

If that can be done reliably, one may be able to perform DNS for specific VM's, while keeping the others on the default Qubes network? Could that make the other VM's immune to potential threats DNS channels would introduce? or does multiple networks somehow open up for new attack surfaces?

**Comment by awokd** [comment]
> safe to construct multiple internal networks

I think that's part of the design: https://theinvisiblethings.blogspot.com/2011/09/playing-with-qubes-networking-for-fun.html

**Comment by taradiddles** [comment]
re- namecoin : interestingly I looked at it 2-3 weeks ago after I noticed [this pull request](https://github.com/QubesOS/qubes-doc/pull/636) in the official qubes docs. Had no time to play with it though.

**Comment by Aekez** [comment]
It really is indeed, maybe we can play around with it someday when we have time for it :)

**Comment by taradiddles** [comment]
fyi - DNS over HTTPS (DoH) as an optional feature in the Firefox browser:

https://lwn.net/Articles/756262/

wondering how they'll solve this:

> How does this interact with the rather common setup where an entity intranet (on an RFC1918 network) is presented through the entitys internal DNS server but not publicly available?

**Comment by awokd** [comment]
Closing for now.
