### ISSUE TITLE
template fails to build due to download failure 

### ISSUE THREAD

**Issue by notspam420** [Qubes-Community/Contents#140]
i was trying to setup arch Linux using the tutorial, when i got to step (6) I got an error saying:
```
make[1]: *** [Makefile:65: rootimg-build] Error 1 this is the error in the Aforementioned log file:

:: Proceed with installation? [Y/n] 
:: Retrieving packages...
 libwacom-1.10-1-x86_64 downloading...
error: failed retrieving file 'libwacom-1.10-1-x86_64.pkg.tar.zst' from mirrors.evowise.com : The requested URL returned error: 404
error: failed retrieving file 'libwacom-1.10-1-x86_64.pkg.tar.zst' from mirror.rackspace.com : The requested URL returned error: 404
error: failed retrieving file 'libwacom-1.10-1-x86_64.pkg.tar.zst' from mirror.rackspace.com : The requested URL returned error: 404
warning: failed to retrieve some files
error: failed to commit transaction (failed to retrieve some files)
Errors occurred, no packages were upgraded.
make[1]: *** [Makefile:65: rootimg-build] Error 1
```
note: was not using tor

**Comment by lubellier** [comment]
Hi @notspam420 ,
  please could you try again?

  I [updated](https://github.com/Qubes-Community/Contents/pull/141) the [ArchLinux build guide](https://github.com/Qubes-Community/Contents/blob/master/docs/building/building-archlinux-template.md) and built a 4.1 template without issue.

  Your error message is about a not found package (404 HTTP code), was it on the mirror repository (rackspace/evowise)? Also, you could try to change the repository mirrors (official [list](https://archlinux.org/mirrors/status/)).

  In my current template, the libwacom package version is *1.12-1*.

  If it failed again, please provide more information (qubes-os target 4.0/4.1, minimal/normal template, qubes builder fedora 32/33/34, ...).

**Comment by awokd** [comment]
>If it failed again, please provide more information (qubes-os target 4.0/4.1, minimal/normal template, qubes builder fedora 32/33/34, ...).
