### ISSUE TITLE
Qubes Windows Tools Makes Win7 VM Slow

### ISSUE THREAD

**Issue by qwthelp** [Qubes-Community/Contents#183]
Hi.

Apologies if this is the incorrect platform for this query.

Ditto title- upon installing Qubes Windows Tools onto an updated Windows 7 VM, processes get much slower.
Programs take much longer to open than without QWT, audio is crackly, network takes minutes to load (ethernet), cursor skips and websites like YouTube fail to load or are very slow.

"qrexec_installed" and "guiagent_installed" do not appear when using the "qvm-prefs" in dom0, though all QWT functions I have tested work correctly, just very slowly.

I have reinstalled both Windows 7 itself and QWT, with the same results.

I've dedicated 4096 MB, 8 VCPUs and 60GB of storage to this VM and I'm running an Intel 7700k processor with 16GB of RAM if it helps.

I appreciate any help. Cheers.

**Comment by taradiddles** [comment]
Hey

This repository is more about publishing community documentation than help/support - you'll get more views posting to the [official Qubes OS forum](https://forum.qubes-os.org/).

fwiw my windows qubes are win10 so I can't help but @GWeck (here on github and on the forum) hasn't reported an issue like yours with the recent version of QWT on R4.1. If you haven't done so yet, you should check those links (assuming you're on R4.1):
- https://forum.qubes-os.org/t/wip-windows-qwt-user-reports/9687
- https://github.com/Qubes-Community/Contents/blob/master/docs/os/windows/windows-vm41.md

Hope this helps !

**Comment by qwthelp** [comment]
Thanks, I'll look into these.
