### ISSUE TITLE
License & disclaimer discussions (protection of users and producers)

### ISSUE THREAD

**Issue by Aekez** [Qubes-Community/Contents#2]
Edit, removing old post content in favor for work-table updates. This is the first update, more will come today. Currently this is very incomplete.

## Legal law, ethics, & morality ##

**1. The art of being fair**
The purpose of this entire page regarding legal law, ethics, & morale, is not to make it easier to sue anyone, nor is it about blindly writing off any responsibility in every possible direction, trying to act innocent. On the contrary, this page is about being fair, to all parties and not just large groups, groups, or smaller minorities, but everyone involved in some sense or another. The hope for this page is to solve any potential emerging conflicts without escalating the disputes, as well as seeking to prevent them to begin with. It is our belief that everything can be talked out and solved, if all involved parties wishes to be fair.    

</br>

**2. Definition of laws, ethics and morality**
Those who know the definitions may skip chapter 2. However, how we as a community relate to these definitions, will be briefly mentioned towards the end of each definition.
- **Defining laws**
  It is often forgotten that laws are social constructs, they are not a natural phenomena, and that they may not necessarily be deemed right either, laws are after all based on values, and values are subjective. A law is also only a law for as long it is being enforced. The moment a law is not being enforced, and a person still believes in the law, then this becomes morality. A group or community with similar morales, share their values through ethics. Laws, ethics and morale is therefore inter-connected with each others. Laws also have boundaries, and may differ from country to country. However while all this is true, there are laws, that are being enforced outside this community to which the community is not immune of. It is important that we identify these laws that matter to the community, and categorize them in order to avoid any laws being broken.

- **Defining ethics**
  Both ethics and morality serves as a placeholder for values, which describe what is believed to be right or wrong. Morality is a placeholder for an individual's beliefs of what is right and wrong, while ethics serves as a placeholder for what a community or a group of people believes is right or wrong. Determining ethics in a group or community, can be tricky, and there may be parallel and overlapping ethics as well. Determining ethics is by no means easy, and so too does ethics change over time, just as values are fluid and changeable.

- **Defining morality**
  Morality can be considered the placeholder for the individuals belief of what the individual believe is right and wrong. Morality can therefore easily be different from one person to the next person. Ethics is often considered a constitution of multiple moralities. How we as a community handle differentiation of morality, may shift and be different depending on the type and kind of relations and interactions the community has with its environment.
</br>

**3. Copyright, & ownership**
Coming.

</br>

**4. Volunteer Communities with international, & multiple national laws**
Being an international volunteer community on the internet, gives rise to major legal challenges. For example, is the issue in the dispute legal or illegal? Which law is being followed in any one country or internationally? Which court will be used? Who to sue if it's all volunteer work and a decentralized community, and with the above international law complications making it harder at that? These are all important questions.

</br>
</br>

**5. Protecting users** 
**5.1. Legal law**
Unfortunately we are not a real organization, so we cannot provide legal protection either, we have no insurances, nor any resources, to do risk analyses, quality checks, damage control, or anything similar of the sorts. We operate strictly on proper ethics and guidelines to try protect our users from poor or damaging content, and bad intentions.

**5.2. Ethics**
Within similar concepts of law, we also operate here with the conceptions of 'good or bad' intentions. Any content shared with the incentive of bad intentions, will be removed, and the individual in question expelled from the community. We will as we grow bigger, try to increase our quality, but this is not something we can promise or make gureeantee's about.

**5.3. Morality**
Striving off the path of community ethics here, can have consequences, especially if harboring bad intentions, which may lead to being excelled from the community.

</br>
</br>

**6. Protecting community producers**
**6.1. Legal law**
This is a volunteer community, any content produced, shared, or otherwise, is considered free of responsibility, and must be used by any user, by any kind of consumption, at own risk. While it is expected that every producer do their best to deliver the best quality they can within their means (that is, having good intentions), producers, the community, or any other involved identity, will however not be accountable for not meeting any quality standards, goals, or promises. Please understand that we do not have the capability to perform risk analyses, quality checks, damage control, nor is this community official in any sense, and for the same reason we don't have an insurance. We therefore need you to understand, that we cannot take this risk, we are not a real organization. Again, any content used, shared and consumed, is completely at own risk.  

**6.2. Ethics**

**6.3. Morality**

</br>
</br>

**7. Protecting 'The Qubes OS Project'**

**7.1. Legal law**
There are no legal ties, laws, agreements, or any official relation, between The Qubes OS Project and Qubes Community Collaboration. Both are considered fully isolated and have independent identities.
 
**7.2. Ethics**
The ethics from the collective community, is that it is ethical to act responsibly towards The Qubes OS Project. By acting responsibly, the collective morale's, the ethic, is to follow the knowledge presented, the listed beliefs, philosophy, and opinions, that take shape officially in The Qubes OS Project. While the Qubes Community Collaboration is independent, we are first and foremost all Qubes OS users, and the general ethics is to take anything that comes from The Qubes OS Project seriously, before anything that comes from this community, which remains secondary. This community only shapes its own identity where there is an empty vacuum to do so.

**7.3. Morality**
Normally morale and freedom of speech allow freedom to say whatever, however, we will transparently in this sub-section transfer location to morality freedom, that is, actions taken based on morality. If you want to oppose The Qubes OS Project's world-view and theoretical frame-work, then this must be done there, and not here in this community. The rationale for this, is because this community has no clear leadership, has no official professionals, does no researching on its own, nor have the capability to objectively search after truths on an epistemological and methodological level. The communities paradigm and world-view is therefore that of The Qubes OS Project, mirroring the same world-view. It is therefore not okay for community users and members to, for example spread content about, for example security, which goes against the paradigm and theoretical work used by The Qubes OS Project. Individual freedom and action from morality is still retained, however you must use this freedom to interact with The Qubes OS Project, this community will take no part in differentiating itself and will retain the same world-view. 

</br>
</br>

**8. Protecting Qubes Community Collaboration**
**8.1. Legal law**
No group, member, user, collaborator, owners, or any identity whatsoever, signed any agreements, or contracts. This is a completely free volunteer community, no one are bound to anything. The tools and resources used, are just that, tools and resources, nothing more, nothing less. We are not an official real organization.

**8.2. Ethics**

**8.3. Morality**

</br>
</br>

**9. Protecting involved and non-involved third-parties**
**9.1. Legal law**
The community as a whole strive to protect third-party property and ownership, copyrights and fair-use agreements. 

**9.2. Ethics**

**9.3. Morality**

</br>
</br>

**10. Conclusively**

</br>
</br>

**Comment by Aekez** [comment]
Currently we have a 'caution before use' here 
https://github.com/Qubes-Community/Qubes-Community
This could probably be done better though.

**Comment by awokd** [comment]
added note to same page about no Qubes endorsement

**Comment by Aekez** [comment]
I'll assign my self to go and collect the resources needed here, once I can find enough time to find everything relevant to this topic. Hopefully we can make a collective overview, and then post it for others to see. If we endorse development here, then there will for example be times when people use other people's work, so it'll be important to remind everyone to check licenses properly, how to assign their own licenses, ownership questions, and so on. Protecting both users and producers.

**Comment by awokd** [comment]
@Aekez Anything here that would prevent us from "opening the doors", or do you think it's good enough for now?

**Comment by Aekez** [comment]
@taradiddles @awokd 
True, lets discuss this later, there is much to be covered. I'll give it an appropriate label and close it.
