### ISSUE TITLE
Binary Qubes-Router - A new way thinking about router security

### ISSUE THREAD

**Issue by Aekez** [Qubes-Community/Contents#20]
**Introduction**
The basic concept of this idea is simple, merging one the core ideas of Qubes, with the widespread known idea of using an old or new cheap Linux computer designated as a router (the binary concept explained further below). Thereby, whenever the Qubes-Router is restarted, all system files and configurations are preserved, while cleaning away any malware or damage from an attack. Note, this idea is not intended for your primary Qubes system, but to be used on an old or cheap computer, designated as a router. Exploring the idea of making a transportable mobile Qubes-Router to bring along with your Qubes laptop and other devices, is also worth thinking about.

**A growing threat**
Currently more and more routers are getting hacked, and it really is becoming a problem. Control the router, and the attacker controls the traffic, either for theft, surveillance, using you for DoS or DDoS attacks, or can even open up a permanent base of operations on your local network. 

**The strength in this router concept**
If removing, or heavily reducing, what can be persistent through a restart, then the only way to make persistent attacks, are to find vulnerabilities in Qubes OS itself. Meaning, routers will be clean every time they are re-started, for as long Qubes OS itself is not successfully attacked. 

**Taking it further - A potential new way of thinking Router security - 'Binary' Qubes-Router**
This idea is to make a dual fall-over system, so that two Qubes-Routers keep restarting, thereby cleaning themselves from any attacks on a consistent basis, without interrupting the network connections. Say for example two Qubes-Routers, which both restarts every 10 minutes, but are sync'ed to stay 5 minutes apart from each others. When one restarts, it hands connections to the other Qubes-Router, and then shuts down. Rinse and repeat. This way, the attacker has a very brief moment to attack the AppVM Router. Whether both Qubes-Routers (AppVM's) should be on the same hardware, or on separate hardware, is also a security question that needs exploring. Further whether handling over traffic from one router to another increases security attack surface or not, also needs exploring. 

**Making the attack surface extremely narrow**
If both routers are restarting on a frequent hasty basis, then the attacker only has a very short window to perform the attack. Failure to do so, means the attacker needs to start over, and any types of attacks that require lengthy performance are ruled out. If the router only has two AppVM's running with internet connection, rotating and restarting, then it could **hypothetically** also be hard to perform any attacks which could potentially breach dom0. 

**This security idea needs backing from security resarchers, for now it is only an hypothesis, nothing more.**
The security of something like this, needs to be verified by professionals, such as the Qubes developers or others working with high-end security. It should, hypothetically speaking, be possible to construct a Binary Qubes-Router without changing Qubes OS itself though.

**Work contribution**
Currently I don't have the time to dig further into this, however I may do so later on. Meanwhile, if anyone is interested, do feel free to contribute, or fully takeover if you're interested in this project.

**Comment by Aekez** [comment]
Does anyone have a good idea for hardware, which is preferably cheap and mobile? Other strengths may also be low watt usage, and the default Qubes 4 hardware recommendation for security is also highly desired. 

I imagine multiple USB or network NIC controllers may not be necessary. One NIC can be used for one of the networks, while the USB controller can be used for the other network. Supposedly it should increase security, but I'm no expert on this.

Anyone has suggestions on how to properly handle the handover of traffic from one router to the other?

**Comment by awokd** [comment]
Not super cheap but https://pcengines.ch/apu2.htm has some type of hardware virtualization support (unknown if enough for 4.0).

**Comment by Aekez** [comment]
> Not super cheap but https://pcengines.ch/apu2.htm has some type of hardware virtualization support (unknown if enough for 4.0).

Amazing find! Besides the price, it just seems perfect. The price is still within the range of acceptable too, but it's indeed still a bit of a risk to take if not knowing if it'll work or not. However it does look a lot like it might just work. Looked a bit around and found this, it seems Xen can run on it with some Coreboot / Xen patches, from around 2016 http://www.pcengines.info/forums/?page=post&id=77FF51E3-8ACA-4B79-BD2C-1380B9B48B5D&fid=DF5ACB70-99C4-4C61-AFA6-4C0E0DB05B2A
It's definitely also a plus that it runs Coreboot. I'd assume if Xen can run on it, with IOMMU, then chances seem good for Qubes, I'm gonna risk it.

I'll give this a try once more of the software has been resolved. Going to experiment with the dual router on a regular Qubes laptop first before getting the hardware.

**Comment by taradiddles** [comment]
FWIW I have an old pcengine alix3d2 board, it's a rock solid piece of hardware - still running strong after many years, only had to replace a worn CF card once.
I heard that the newer boards based on APUs were running hot though - you might check that before you buy one.

**Comment by Aekez** [comment]
@taradiddles 
Thanks! It's good to have hardware to pick between, might try them both if I can. Do you by any chance know if it works with IOMMU and Xen/Qubes?

**Plan thus far: Might be modified, early layout.**

![screenshot_2018-04-25_21-47-49](https://user-images.githubusercontent.com/33869013/39269216-c81a4642-48c1-11e8-8cb6-2196b2269308.png)

**Binary Qubes-Router (AppVM#1) & (AppVM#2)**
Installing OpenWRT as AppVM, using the 86_64 infrastructure (To be tested, currently only in idea phase). 
- OpenWRT Binary download https://downloads.openwrt.org/releases/17.01.4/targets/x86/64/
  - Can also be compiled, but cutting shortcuts in concept phases.
- OpenWRT Bootloading https://wiki.openwrt.org/doc/techref/process.boot
- VRRP (Virtual Router Redundancy Protocol) https://wiki.openwrt.org/doc/recipes/high-availability
<br />

**Qubes OS**
No modifications done or needed for Qubes OS itself, except perhaps for small adjustments in AppVM policy behaviors.
<br />

**Qubes Network**
Outside the scope of this topic, however is illustrated to show the full potential Binary Qubes-Router.
QubesTV, Qubes-NAS, etc. are other projects already being worked on.
<br />

**Comment by Aekez** [comment]
**A gradually growing and adjusted collection of papers of interest to the topic**
- Virtual Router Redundancy Protocol (VRRP), the initial concept, 1998. https://datatracker.ietf.org/doc/rfc2338/?include_text=1 
- Virtual Router Redundancy Protocol (VRRP), 2004. https://datatracker.ietf.org/doc/rfc3768/?include_text=1
- Virtual Router Redundancy Protocol (VRRP),  Introduction to VRRP, 2000. https://www.scribd.com/document/29316984/VRRP
- L2 Switch Feature for Virtual Router Redundancy Protocol Fast Convergence, 2012. https://pdfs.semanticscholar.org/4726/f61412ff865e493c6c0258188cd11dc0c6cd.pdf
- Digi's take on "WAN Failover Scenarios - Using Digi Wireless WAN Routers", 2008. https://www.digi.com/pdf/appguide_cellular_wan_backup.pdf
- VRRP Protocol whitepaper, 2002. Paper seems unpolished, i.e. obvious missing finish on page 2, pages 20-21. That does not rule out the reliability of the paper, but it does put it into bigger question of reliability considering these mistakes are very easy to spot, and very easy to avoid making in a proper paper. Nonetheless, worth checking out for inspiration and insights to search and double-check/confirm elsewhere. http://www2.elo.utfsm.cl/~tel242/exp/04/VRRP_protocol.pdf

Far from done looking for papers and articles, will update this post when I find more papers and articles, out of time for today.

**Comment by eduncan911** [comment]
Oh my... I am currently doing this on my own, just now getting to the tubes messaging/db parts and building them. :)  This is going to be awesome... 

BTW, the hardware I am using is an UP Squared board. https://up-board.org/upsquared/specifications/ 

Fully supports IOMMU, VTd, AES, etc with dual Gigabit nics and goes up to 8 GB ram.  They also have a new UP Core Plus board that had a 4-port Gigabit expander with Intel NICs that I may pick up.

Now, I originally started down a different path and have some of the networking completednwith iptables and netbacks in isolated sys-net VMs (two of them, to isolate WAN from LAN traffic) with a sys-firewall inbetween. 

For dom0, to keep it isolated but without qubes messaging working, I simply threw in an M.2 WiFi card and am currently passing it to dom0 for now connected to a dedicated VLAN that is air-gapped on my home network so can remotely manage the device for now.

Lastly, I am using Arch Linux as dom0 that gives me the latest Xen 4.11 (4.10 goes EOL in June 2019).  Another reason is that Qubes' old fedora versions and kernels have bit me a few times on some of these newer devices (have to have a recent kernel for the recent Intel chipsets in these UP devices).

The downside of going ArchLinux of course is I am building all the Qubes layers up from scratch.  I have found where the latest Xen versions have incorporated quite a lot of the Qubes messaging protocols as Qubes does contribute back to Xen. It's just a matter of getting the Qubes tools built

**Comment by eduncan911** [comment]
Reading about the Binary Router concept... There's going to be a inherit issue that may put off a lot of folks and that is long-lived connections.  E.g. OpenVPN, or even recent HTTP/2 websites as gRPC expects a single long live connection (at my current gig, we go up to 12 hours for single connections to lower bandwidth over millions of requests per second - when a connection does get reset, our machines CPU and network I/O goes through the roof).

Great idea though.  Maybe a compromise would be to reboot the `sys-wan` every 12 or 24 hours.  That was my plan, once I have templates and cloning completed.

**Comment by awokd** [comment]
Closing for now.
