### ISSUE TITLE
Where to store content?

### ISSUE THREAD

**Issue by one7two99** [Qubes-Community/Contents#25]
I would like migrate most of my scripts and installation notes over to this repository but I feel that it is not clear where to store the content in the repository as we have docs / code / etc.
Can we rearrange this or should I just throw the stuff in and we decide later on where to move it?
In my own repository I have the following categories:

- general = general linux tips
- docs = howtos how to build stuff and implement features. if something needs more files I put it into subfolders

If I move content into the qubes-community repository I would like to track "my scripts" in case I need to reinstall my system. Is there any smart way to do so, like using labels?
I don't want to store thinks in two locations (my private repository and the qubes-community-docs).

[799]

**Comment by awokd** [comment]
I think general and docs in your case would fit under docs here, couldn't they? Code would be more for scripts. Another option could be to just add links to your repo from here, like we did for some of tasket's. Would that work better?

**Comment by one7two99** [comment]
awokd <notifications@github.com> schrieb am Do., 3. Mai 2018, 23:42:

> I think general and docs in your case would fit under docs here, couldn't
> they?
>
Ok, I will add content there and then we might re-arrange

Code would be more for scripts. Another option could be to just add links
> to your repo from here, like we did for some of tasket's. Would that work
> better?
>

No, as I would like that other people have an easy option to work on the
code and a single space to browse scripts.
Often I get ideas how to build stuff viewing the code of others.

[799]

>

**Comment by Aekez** [comment]
@one7two99 
There is also the possibility of first keeping it at your own github page, and then instead linking the scripts and content back here. This allows you to store it the way you prefer, while also showing it on here the preferred way through links. Could give you more flexibility, possible win-win scenario?

**Comment by one7two99** [comment]
Hello Yuraeitha,

How does this (linking) works?

[799]

Yuraeitha <notifications@github.com> schrieb am Fr., 4. Mai 2018, 22:25:

**Comment by one7two99** [comment]
Yes

awokd <notifications@github.com> schrieb am Fr., 11. Mai 2018, 14:23:

**Comment by awokd** [comment]
Closing!
