### ISSUE TITLE
Qubes Split SSH: specify that the path to the key file in the .desktop file should be absolute

### ISSUE THREAD

**Issue by tungsten987** [Qubes-Community/Contents#261]
In the [Qubes Split SSH guide](https://github.com/Qubes-Community/Contents/blob/ed0f4b6586381859fb6f1dd33b88f7fdc34d9f02/docs/configuration/split-ssh.md), when following the non-KeePassXC route, the user is advised to create a `~/.config/autostart/ssh-add.desktop` in their `vault` AppVM containing the line `Exec=ssh-add -c`.

The guide then advises:

> **Note:** If you've specified a custom name for your key using _-f_, you should adjust `Exec=ssh-add` to `Exec=ssh-add <path-to-your-key-file>`.

What the guide _doesn't_ specify is that the `<path-to-your-key-file>` cannot reference the user home directory with a `~`, the path must be absolute (e.g. `/home/user/.ssh/my_key` instead of `~/.ssh/my_key`).

So, I suggest changing the excerpt quoted above to (also keeping the `-c` option for consistency):

> **Note:** If you've specified a custom name for your key using _-f_, you should adjust `Exec=ssh-add -c` to `Exec=ssh-add -c <path-to-your-key-file>` (the path must be absolute, e.g. `/home/user/.ssh/my_key`).

**Comment by taradiddles** [comment]
Thanks, I'll update the instructions. Alternatively you could either submit a PR, or edit the doc in the forum once it's migrated (see #257) - let me know what you prefer.

**Comment by tungsten987** [comment]
Alright I tried to submit a PR, see above. I hope it worked (first time I do this).

**Comment by taradiddles** [comment]
Thank you. Merged...
By the way - as mentioned in #257 - are you OK to have your contribution(s)'s license be CC BY 4.0?

**Comment by tungsten987** [comment]
Thanks for the merge. Yes, I'm okay with licensing my contributions under CC BY 4.0. I'm not registered on the forum yet, I guess I'll do that if I need to contribute again after the migration?

**Comment by taradiddles** [comment]
> I'm not registered on the forum yet, I guess I'll do that if I need to contribute again after the migration?

Yes!

**Comment by awokd** [comment]
Content moved to https://forum.qubes-os.org/c/guides/14.
