### ISSUE TITLE
Doc suggestion: Qubes Inheritance and Persistence Table

### ISSUE THREAD

**Issue by adrelanos** [Qubes-Community/Contents#42]
https://www.whonix.org/wiki/Template:Qubes_persistence

**Comment by awokd** [comment]
Hi @adrelanos ! Are you looking for the above to be added somewhere in the official Qubes docs, or just described a bit more on the Whonix wiki?

**Comment by adrelanos** [comment]
awokd:
> Are you looking for the above to be added somewhere in the official Qubes docs

Yes.

**Comment by awokd** [comment]
https://www.qubes-os.org/doc/templates/#important-notes-r40
