### ISSUE TITLE
Rename repository

### ISSUE THREAD

**Issue by one7two99** [Qubes-Community/Contents#44]
hello,

I have cloned the Qubes-Community repository and found out that the resulting directory on my laptop just has the name "contents", it should be something more clear, something like "qubes-community-doc" which is much better.

I have run the following steps:
git clone git@github.com:Qubes-Community/Contents.git

Can someone rename the directory/repository to "qubes-community-doc" instead of "contents"?

[799]

**Comment by taradiddles** [comment]
Hey,

We discussed that some time ago; "Contents/" was preferred over "qubes-community-contents" in order not to duplicate the "Qubes Community" organization with repos and make it visually nicer for people reaching the site through github.

Duplication concerns aside, renaming the repo now will probably break links to it (not sure Github has a redirection mechanism).
"git clone" is already a bit "power user", why not simply create a "qubes-community" parent folder and git clone "contents/" inside it ? (that's what I've done).

**Comment by one7two99** [comment]
Hello Ivan,

> We discussed that some time ago; "Contents/" was preferred over
> "qubes-community-contents" in order not to duplicate the "Qubes Community"
> organization with repos and make it visually nicer for people reaching the
> site through github.
>
Ok, sounds like an argument :-)
It was just cumbersome to have this contents directory, I think creating a
qubes-community folder and then cloning into this subdirectory is coming xx
see we



Duplication concerns aside, renaming the repo now will probably break links
