### ISSUE TITLE
add gaming hvm doc

### ISSUE THREAD

**Issue by awokd** [Qubes-Community/Contents#61]
Hi, @neowutran! Could you please submit that gaming HVM doc to https://github.com/Qubes-Community/Contents/tree/master/docs/customization, or let me know if you want me to copy&paste? Prefer you do it so it keeps authorship, but I can if you want.

**Comment by neowutran** [comment]
Hey ! I will submit it soon, checking some modifications with the ``permissive`` flags

**Comment by awokd** [comment]
I'm surprised that `permissive` is not required. AMD made some better hardware than I thought.

**Comment by awokd** [comment]
Thanks again, @neowutran. Mind following up to the qubes-users mailing list with a link to it at https://github.com/Qubes-Community/Contents/blob/master/docs/customization/windows-gaming-hvm.md? Will close this out.
