### ISSUE TITLE
Howto: Setting default terminal settings for a TemplateVM

### ISSUE THREAD

**Issue by tetrahedras** [Qubes-Community/Contents#73]
Not sure where I should put this...

# Setting default terminal settings for a TemplateVM

When you create a VM based on a TemplateVM, the `gnome-terminal` settings (font, color) are not inherited by default. This document describes how to set terminal defaults for all VMs *subsequently* created off a TemplateVM.

(Previously-created VMs are unaffected.)

This document only applies to `gnome-terminal` (the standard terminal)
and not XTerm, etc.

Thanks to `unman` on qubes-users for explaining how to do this.

## Define your defaults

In dom0:
`qvm-run MYTEMPLATE gnome-terminal`

In the terminal that pops up, adjust settings to your liking.

## Save settings template-wide

In the templateVM's terminal:
```
sudo mkdir -p /etc/skel/.config/dconf
sudo cp ~/.config/dconf/user /etc/skel/.config/dconf/
sudo reboot
```

Subsequently-created VMs should now use the chosen settings by default.

**Comment by awokd** [comment]
Could you submit to https://github.com/Qubes-Community/Contents/tree/master/docs/customization, and include a link to it in the parent folder's readme? I can copy and paste it over there if you want, but it breaks attribution so would prefer you.

**Comment by tetrahedras** [comment]
Realistically I am so busy that it will be a long time before I get
around to doing that, and I don't care about attribution. feel free to
copy and paste

**Comment by awokd** [comment]
Thank you, @tetrahedras !
