### ISSUE TITLE
Pi Hole 

### ISSUE THREAD

**Issue by 92VV3M42d3v8** [Qubes-Community/Contents#94]
Hello, there. I have an updated version of Pihole qube documentation which works with cloudflared and NextDNS servers. It's mostly based on Patrizio work though. But I also experimented with some tweaks. If you like we can include that in community doc.
https://github.com/92VV3M42d3v8/PiHole/blob/master/PiHole%20Cloudflared

**Comment by awokd** [comment]
Added: https://github.com/Qubes-Community/Contents/pull/95. Thank you.
