### ISSUE TITLE
Qubes RPC policies

### ISSUE THREAD

**Issue by 92VV3M42d3v8** [Qubes-Community/Contents#97]
In user setups, it would be great to show some user configured RPC policy files. like -
        *     *      @anyvm   Vault   deny
What do you guys think about it. There is no one shoe fit all option but How security critical vm are handled by long time users can benefit other new users.

**Comment by awokd** [comment]
Seems fine with me if people are willing to share them or parts of them. What change should we make to the site, though?

**Comment by awokd** [comment]
Might be worth asking for contributions on the mailing list and/or forum? Closing this for now, though!
